### ISSUE TITLE
Preloading .dll or .so Files

### ISSUE THREAD

**Issue by WhitePeace36** [arunanshub/preload-rs#69]
Hi, this is more of a question than anything else. Does this app also preload resources like .dll, .so and other files into the memory ?

**Comment by WhitePeace36** [comment]
Thank you for the answer :) So when i run something through wine and that .exe has dll files they also dynamically loaded ?

**Comment by arunanshub** [comment]
You're welcome 😄 preload-rs has nothing to do with windows executables and its shared libraries because we exclusively use posix API (readahead, fadvise etc). Wine is just a compatibility layer. However there is a silver lining because Wine is just a wrapper, so preload-rs will notice that and load the necessary *linux only* shared libraries onto the memory to speed up execution.

 Also note that if you're using an SSD, you don't actually need preload-rs.

**Comment by WhitePeace36** [comment]
Ok thanks :)

So it isn't useful when i have m2 ssds ?

**Comment by arunanshub** [comment]
Nope, I believe you don't need it. Because your M.2 SSDs are fast enough for your system to load the shared libraries almost instantaneously. And if you have a fairly recent CPU then double bingo!

**Comment by WhitePeace36** [comment]
Ok, thank you mate :)
